export enum EmailTemplate {
    EMAIL_VERIFICATION = "4455",
    AFFILIATE_VERIFICATION = "4461",
    RESET_PASSWORD = "4512",
    AFFILIATE_APPLICATION_ACKNOWLEDGEMENT = "4545",
    WELCOME_AFFILIATE = "4515",
    AFFILIATE_APPLICATION_ACCEPTED = "4461",
    AFFILIATE_APPLICATION_REJECTED = "4515",
}